import type { Metadata } from "next";
import { Geist, Geist_Mono, Forum } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import ServiceWorkerRegister from "@/components/pwa/ServiceWorkerRegister";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const forum = Forum({
  variable: "--font-forum",
  subsets: ["latin", "cyrillic"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${forum.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white">
        {/* Navbar — бүх public хуудаст тогтмол; dashboard/admin route-уудад
            өөрөө null буцаадаг (Navbar.jsx HIDDEN_PREFIXES үз). */}
        <Navbar />
        {children}
        <ServiceWorkerRegister />
      </body>
    </html>
  );
}
